package org.zawamod.zawa.world.entity.animal;

import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import org.zawamod.zawa.Zawa;

/** First concrete ZAWA species batch recovered from the original 1.20.1 build. */
public final class ZawaEntities {
    private ZawaEntities() {}
    public static final DeferredRegister<EntityType<?>> REGISTRAR = DeferredRegister.create(Registries.ENTITY_TYPE, Zawa.MOD_ID);

    public static final DeferredHolder<EntityType<?>, EntityType<AfricanLion>> AFRICAN_LION = REGISTRAR.register("african_lion", () -> EntityType.Builder.of(AfricanLion::new, MobCategory.CREATURE).sized(1.3F, 1.4F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "african_lion"))));
    public static final DeferredHolder<EntityType<?>, EntityType<AfricanWildDog>> AFRICAN_WILD_DOG = REGISTRAR.register("african_wild_dog", () -> EntityType.Builder.of(AfricanWildDog::new, MobCategory.CREATURE).sized(0.9F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "african_wild_dog"))));
    public static final DeferredHolder<EntityType<?>, EntityType<AsianElephant>> ASIAN_ELEPHANT = REGISTRAR.register("asian_elephant", () -> EntityType.Builder.of(AsianElephant::new, MobCategory.CREATURE).sized(3.0F, 3.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "asian_elephant"))));
    public static final DeferredHolder<EntityType<?>, EntityType<BaldEagle>> BALD_EAGLE = REGISTRAR.register("bald_eagle", () -> EntityType.Builder.of(BaldEagle::new, MobCategory.CREATURE).sized(0.8F, 1.2F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "bald_eagle"))));
    public static final DeferredHolder<EntityType<?>, EntityType<BlackFootedFerret>> BLACK_FOOTED_FERRET = REGISTRAR.register("black_footed_ferret", () -> EntityType.Builder.of(BlackFootedFerret::new, MobCategory.CREATURE).sized(0.6F, 0.6F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "black_footed_ferret"))));
    public static final DeferredHolder<EntityType<?>, EntityType<CommonChimpanzee>> COMMON_CHIMPANZEE = REGISTRAR.register("common_chimpanzee", () -> EntityType.Builder.of(CommonChimpanzee::new, MobCategory.CREATURE).sized(0.8F, 1.4F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "common_chimpanzee"))));
    public static final DeferredHolder<EntityType<?>, EntityType<CoquerelsSifaka>> COQUERELS_SIFAKA = REGISTRAR.register("coquerels_sifaka", () -> EntityType.Builder.of(CoquerelsSifaka::new, MobCategory.CREATURE).sized(0.7F, 0.9F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "coquerels_sifaka"))));
    public static final DeferredHolder<EntityType<?>, EntityType<EmperorPenguin>> EMPEROR_PENGUIN = REGISTRAR.register("emperor_penguin", () -> EntityType.Builder.of(EmperorPenguin::new, MobCategory.CREATURE).sized(0.6F, 1.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "emperor_penguin"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Flamingo>> FLAMINGO = REGISTRAR.register("flamingo", () -> EntityType.Builder.of(Flamingo::new, MobCategory.CREATURE).sized(0.7F, 1.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "flamingo"))));

    public static final DeferredHolder<EntityType<?>, EntityType<SumatranOrangutan>> SUMATRAN_ORANGUTAN = REGISTRAR.register("sumatran_orangutan", () -> EntityType.Builder.of(SumatranOrangutan::new, MobCategory.CREATURE).sized(1.0F, 1.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "sumatran_orangutan"))));
    public static final DeferredHolder<EntityType<?>, EntityType<TreeFrog>> TREE_FROG = REGISTRAR.register("tree_frog", () -> EntityType.Builder.of(TreeFrog::new, MobCategory.CREATURE).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "tree_frog"))));
    public static final DeferredHolder<EntityType<?>, EntityType<WesternLowlandGorilla>> WESTERN_LOWLAND_GORILLA = REGISTRAR.register("western_lowland_gorilla", () -> EntityType.Builder.of(WesternLowlandGorilla::new, MobCategory.CREATURE).sized(1.2F, 1.8F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "western_lowland_gorilla"))));

    public static final DeferredHolder<EntityType<?>, EntityType<GiantAnteater>> GIANT_ANTEATER = REGISTRAR.register("giant_anteater", () -> EntityType.Builder.of(GiantAnteater::new, MobCategory.CREATURE).sized(1.1F, 1.2F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "giant_anteater"))));
    public static final DeferredHolder<EntityType<?>, EntityType<GiantPanda>> GIANT_PANDA = REGISTRAR.register("giant_panda", () -> EntityType.Builder.of(GiantPanda::new, MobCategory.CREATURE).sized(1.4F, 1.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "giant_panda"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Giraffe>> GIRAFFE = REGISTRAR.register("giraffe", () -> EntityType.Builder.of(Giraffe::new, MobCategory.CREATURE).sized(1.5F, 3.4F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "giraffe"))));
    public static final DeferredHolder<EntityType<?>, EntityType<GrevysZebra>> GREVYS_ZEBRA = REGISTRAR.register("grevys_zebra", () -> EntityType.Builder.of(GrevysZebra::new, MobCategory.CREATURE).sized(1.3F, 1.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "grevys_zebra"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Hornbill>> HORNBILL = REGISTRAR.register("hornbill", () -> EntityType.Builder.of(Hornbill::new, MobCategory.CREATURE).sized(0.7F, 0.9F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "hornbill"))));
    public static final DeferredHolder<EntityType<?>, EntityType<IndianGharial>> INDIAN_GHARIAL = REGISTRAR.register("indian_gharial", () -> EntityType.Builder.of(IndianGharial::new, MobCategory.CREATURE).sized(1.2F, 0.8F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "indian_gharial"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Kakapo>> KAKAPO = REGISTRAR.register("kakapo", () -> EntityType.Builder.of(Kakapo::new, MobCategory.CREATURE).sized(0.7F, 0.8F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "kakapo"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Koala>> KOALA = REGISTRAR.register("koala", () -> EntityType.Builder.of(Koala::new, MobCategory.CREATURE).sized(0.7F, 0.9F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "koala"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Macaw>> MACAW = REGISTRAR.register("macaw", () -> EntityType.Builder.of(Macaw::new, MobCategory.CREATURE).sized(0.7F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "macaw"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Mandrill>> MANDRILL = REGISTRAR.register("mandrill", () -> EntityType.Builder.of(Mandrill::new, MobCategory.CREATURE).sized(0.9F, 1.1F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "mandrill"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Orca>> ORCA = REGISTRAR.register("orca", () -> EntityType.Builder.of(Orca::new, MobCategory.WATER_CREATURE).sized(2.0F, 1.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "orca"))));
    public static final DeferredHolder<EntityType<?>, EntityType<ZawaPolarBear>> POLAR_BEAR = REGISTRAR.register("polar_bear", () -> EntityType.Builder.of(ZawaPolarBear::new, MobCategory.CREATURE).sized(1.4F, 1.6F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "polar_bear"))));
    public static final DeferredHolder<EntityType<?>, EntityType<RedKangaroo>> RED_KANGAROO = REGISTRAR.register("red_kangaroo", () -> EntityType.Builder.of(RedKangaroo::new, MobCategory.CREATURE).sized(1.0F, 1.6F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "red_kangaroo"))));
    public static final DeferredHolder<EntityType<?>, EntityType<RedPanda>> RED_PANDA = REGISTRAR.register("red_panda", () -> EntityType.Builder.of(RedPanda::new, MobCategory.CREATURE).sized(0.8F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "red_panda"))));
    public static final DeferredHolder<EntityType<?>, EntityType<RingTailedLemur>> RING_TAILED_LEMUR = REGISTRAR.register("ring_tailed_lemur", () -> EntityType.Builder.of(RingTailedLemur::new, MobCategory.CREATURE).sized(0.7F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "ring_tailed_lemur"))));
    public static final DeferredHolder<EntityType<?>, EntityType<Sloth>> SLOTH = REGISTRAR.register("sloth", () -> EntityType.Builder.of(Sloth::new, MobCategory.CREATURE).sized(0.7F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "sloth"))));
    public static final DeferredHolder<EntityType<?>, EntityType<SnowLeopard>> SNOW_LEOPARD = REGISTRAR.register("snow_leopard", () -> EntityType.Builder.of(SnowLeopard::new, MobCategory.CREATURE).sized(1.0F, 1.1F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "snow_leopard"))));
    public static final DeferredHolder<EntityType<?>, EntityType<SpiderMonkey>> SPIDER_MONKEY = REGISTRAR.register("spider_monkey", () -> EntityType.Builder.of(SpiderMonkey::new, MobCategory.CREATURE).sized(0.7F, 1.1F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "spider_monkey"))));

    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.AfricanLakeCichlid>> AFRICAN_LAKE_CICHLID = REGISTRAR.register("african_lake_cichlid", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.AfricanLakeCichlid::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "african_lake_cichlid"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Angelfish>> ANGELFISH = REGISTRAR.register("angelfish", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Angelfish::new, MobCategory.WATER_AMBIENT).sized(1.2F, 1.8F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "angelfish"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Betta>> BETTA = REGISTRAR.register("betta", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Betta::new, MobCategory.WATER_AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "betta"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Clownfish>> CLOWNFISH = REGISTRAR.register("clownfish", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Clownfish::new, MobCategory.WATER_AMBIENT).sized(0.8F, 1.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "clownfish"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.ZawaCod>> COD = REGISTRAR.register("cod", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.ZawaCod::new, MobCategory.WATER_AMBIENT).sized(1.0F, 0.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "cod"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Corydoras>> CORYDORAS = REGISTRAR.register("corydoras", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Corydoras::new, MobCategory.WATER_AMBIENT).sized(0.7F, 0.9F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "corydoras"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Gramma>> GRAMMA = REGISTRAR.register("gramma", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Gramma::new, MobCategory.WATER_AMBIENT).sized(0.7F, 0.8F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "gramma"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Plecostomus>> PLECOSTOMUS = REGISTRAR.register("plecostomus", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Plecostomus::new, MobCategory.WATER_AMBIENT).sized(3.5F, 2.0F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "plecostomus"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.ZawaSalmon>> SALMON = REGISTRAR.register("salmon", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.ZawaSalmon::new, MobCategory.WATER_AMBIENT).sized(0.5F, 0.5F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "salmon"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Butterfly>> BUTTERFLY = REGISTRAR.register("butterfly", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Butterfly::new, MobCategory.AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "butterfly"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.BrownRat>> BROWN_RAT = REGISTRAR.register("brown_rat", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.BrownRat::new, MobCategory.AMBIENT).sized(0.5F, 0.4F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "brown_rat"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.HoneyBee>> HONEY_BEE = REGISTRAR.register("honey_bee", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.HoneyBee::new, MobCategory.AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "honey_bee"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.LeafcutterAnt>> LEAFCUTTER_ANT = REGISTRAR.register("leafcutter_ant", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.LeafcutterAnt::new, MobCategory.AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "leafcutter_ant"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.PrayingMantis>> PRAYING_MANTIS = REGISTRAR.register("praying_mantis", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.PrayingMantis::new, MobCategory.AMBIENT).sized(0.5F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "praying_mantis"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Scorpion>> SCORPION = REGISTRAR.register("scorpion", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Scorpion::new, MobCategory.AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "scorpion"))));
    public static final DeferredHolder<EntityType<?>, EntityType<org.zawamod.zawa.world.entity.ambient.Tarantula>> TARANTULA = REGISTRAR.register("tarantula", () -> EntityType.Builder.of(org.zawamod.zawa.world.entity.ambient.Tarantula::new, MobCategory.AMBIENT).sized(0.3F, 0.3F).clientTrackingRange(10).build(ResourceKey.create(Registries.ENTITY_TYPE, ResourceLocation.fromNamespaceAndPath(Zawa.MOD_ID, "tarantula"))));

    public static void register(IEventBus bus) { REGISTRAR.register(bus); }
}
