modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ZAWA-Evolved/ZAWA/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/ZAWA-Evolved/ZAWA/main/versions.json"
displayURL="https://github.com/ZAWA-Evolved/ZAWA/wiki"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.zawa]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.zawa]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
